-- MySQL Script generated by MySQL Workbench
-- Mon May 28 15:16:05 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema chayds_teste
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema chayds_teste
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chayds_teste` DEFAULT CHARACTER SET utf8 ;
USE `chayds_teste` ;

-- -----------------------------------------------------
-- Table `chayds_teste`.`tb_cliente`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chayds_teste`.`tb_cliente` (
  `id_clien` INT NOT NULL AUTO_INCREMENT,
  `nome_clien` VARCHAR(50) NOT NULL,
  `sexo_clien` CHAR(1) NULL,
  `cpf_clien` CHAR(14) NOT NULL,
  `email_clien` VARCHAR(60) NOT NULL,
  `senha_clie` VARCHAR(16),
  PRIMARY KEY (`id_clien`),
  UNIQUE INDEX `cpf_clien_UNIQUE` (`cpf_clien` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;