-- MySQL Script generated by MySQL Workbench
-- Fri Jun  8 11:32:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chayds_teste` DEFAULT CHARACTER SET utf8 ;
USE `chayds_teste` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chayds_teste`.`tb_produto` (
  `id_prod` INT NOT NULL AUTO_INCREMENT,
  `nome_prod` VARCHAR(50) NOT NULL,
  `cod_inter_prod` VARCHAR(35) NOT NULL,
  `dt_cad_prod` DATE NOT NULL,
  `descri_prod` VARCHAR(50) NOT NULL,
  `quant_prod` INT NOT NULL,
  `public_alvo` VARCHAR(50) NULL,
  `cod_barras_prod` VARCHAR(25) NOT NULL,
  `nome_forne_prod` VARCHAR(45) NOT NULL,
  `preco_custo` FLOAT NOT NULL,
  `preco_venda` FLOAT NOT NULL,
  `coment_prod` VARCHAR(220) NULL,
  PRIMARY KEY (`id_prod`),
  UNIQUE INDEX `nome_prod_UNIQUE` (`nome_prod` ASC),
  UNIQUE INDEX `cod_inter_prod_UNIQUE` (`cod_inter_prod` ASC),
  UNIQUE INDEX `cod_barras_prod_UNIQUE` (`cod_barras_prod` ASC))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;