-- MySQL Script generated by MySQL Workbench
-- Fri Jun  8 11:32:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chayds_teste` DEFAULT CHARACTER SET utf8 ;
USE `chayds_teste` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_compra`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chayds_teste`.`tb_compra` (
  `id_comp_usu` INT NOT NULL AUTO_INCREMENT,
  `cod_comp_usu` INT,
  `nome_comp_usu` VARCHAR(50) NOT NULL,
  `email_comp_usu` VARCHAR(60) NOT NULL,
  `nome_prod_usu` VARCHAR(50) NOT NULL,
  `quant_prod_usu` INT NOT NULL,
  `dt_comp_usu` DATE NOT NULL,
  `val_uni_comp_usu` DECIMAL(10,2),
  `val_frete_comp_usu` DECIMAL(10,2),
  `val_comp_usu` DECIMAL(10,2) NOT NULL,
  `cpf_comp_usu` VARCHAR(18) NOT NULL,
  `coment_comp_usu` VARCHAR(220),
  `status_comp_usu` INT,
  `status_int_comp_usu` INT,
  `tp_fret_comp_usu` VARCHAR(15),
  `cod_rastr_comp_usu` VARCHAR(20),
  PRIMARY KEY (`id_comp_usu`)
  )
GO
INSERT INTO tb_compra VALUES(1,'Alessandro dos Santos','alessandro@chayds.com.br','Vita Chayds youg live',5,curdate(),25.00,25.00,25.00,'123456789','Nada','0','0'),
(2,'Alessandro dos Santos','alessandro@chayds.com.br','Vita Chayds youg live',5,curdate(),25.00,25.00,25.00,'123456789','Nada','0','0'),
(3,'Teste','alessandro@chayds.com.br','Vita Chayds youg live',5,curdate(),25.00,25.00,25.00,'123456789','Nada','0','0'),
(4,'Alessandro dos Santos','alessandro@chayds.com.br','Vita Chayds youg live',25.00,25.00,25.00,'123456789','Nada','0','0')
GO
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;