-- MySQL Script generated by MySQL Workbench
-- Fri Jun  8 11:32:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chayds_teste` DEFAULT CHARACTER SET utf8 ;
USE `chayds_teste` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chayds_teste`.`tb_funcionario` (
  `id_func` INT NOT NULL AUTO_INCREMENT,
  `nome_func` VARCHAR(50) NOT NULL,
  `num_registro_func` INT(16) NOT NULL,
  `num_rg_func` VARCHAR(18) NOT NULL,
  `num_cpf_func` VARCHAR(18) NOT NULL,
  `cargo_func` VARCHAR(35) NOT NULL,
  `data_nasc_func` DATE NOT NULL,/*Deve vir de outra tabela*/
  `escol_func` VARCHAR(35) NOT NULL,
  `sexo_func` CHAR(1) NOT NULL,
  `nome_depart_func` VARCHAR(50) NOT NULL,/*deve vir da tabela  depart*/
  `email_func` VARCHAR(60) NOT NULL,
  `tel_func_1` VARCHAR(15) NOT NULL,
  `tel_func_2` VARCHAR(15) NULL,
  `senha_func` VARCHAR(16) NOT NULL,
  `gerente_resp_func` VARCHAR(50) NOT NULL,/*deve vir  de outra tabela*/
  `end_func` VARCHAR(40) NOT NULL,
  `complemento_func` VARCHAR(35) NULL,
  `bairro_func` VARCHAR(35) NULL,
  `cidade_func` VARCHAR(35) NOT NULL,
  `estado_func` CHAR(2) NOT NULL,
  `cep_func` VARCHAR(9) NOT NULL,
  `data_contrat` DATE NOT NULL,
  `coment_func` VARCHAR(220),
  `data_demis` DATE,
  `coment_func_demis` VARCHAR(220),
  PRIMARY KEY (`id_func`),
  UNIQUE INDEX `num_registro_func_UNIQUE` (`num_registro_func` ASC),
  UNIQUE INDEX `num_cpf_func_UNIQUE` (`num_cpf_func` ASC),
  UNIQUE INDEX `num_rg_func` (`num_rg_func` ASC)
  )

GO
INSERT INTO tb_funcionario VALUES(1,'Alessandro dos Santos','00020181','1800011','123456','Gerente de TI','2018-01-05','Ensino Superior(Cursando)','M','Tecnologia da informacao(TI)','alessandro@chayds.com.br','(13)99644-2358','(13)3342-4849','123456','Alessandro dos Santos','Rua Dona Risoleta de Moraes N28','Casa A','Jardim Progresso','Guaruja','SP','1463-080','2018-05-01','Nada',NULL,NULL),
(2,'Everton Chayd','0000020182','1800012','1234562','Gerente de negocios','2018-01-05','Ensino Superior','M','Negocios','Evertono@chayds.com.br','(13)99644-2358','(13)3342-4849','123456','Everton Chayd','Rua Dona Risoleta de Moraes N28','Casa A','Jardim Progresso','Guaruja','SP','1463-080','2018-05-01','Nada',NULL,NULL),
(3,'Teste','0000020183','1800013','1234563','Teste','2018-01-05','Ensino Superior teste','M','Teste','alessandro@chayds.com.br','(13)99644-2358','(13)3342-4849','123456','Alessandro dos Santos','Rua Dona Risoleta de Moraes N28','Casa A','Jardim Progresso','Guaruja','SP','1463-080','2018-05-01','Nada',NULL,NULL)
GO

ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;