-- MySQL Script generated by MySQL Workbench
-- Fri Jun  8 11:32:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chayds_teste` DEFAULT CHARACTER SET utf8 ;
USE `chayds_teste` ;

-- -----------------------------------------------------
-- Table `mydb`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chayds_teste`.`tb_produto` (
  `id_prod` INT NOT NULL AUTO_INCREMENT,
  `nome_prod` VARCHAR(50) NOT NULL,
  `vl_alt_prod` INT,
  `vl_larg_prod` INT,
  `vl_cmpri_prod` INT,
  `vl_peso_prod` FLOAT,
  `cod_inter_prod` INT,
  `dt_cad_prod` DATE NOT NULL,
  `descri_prod` VARCHAR(50) NOT NULL,
  `quant_prod` INT NOT NULL,
  `quant_min_prod` INT NOT NULL,
  `public_alvo` VARCHAR(50) NULL,
  `cod_barras_prod` VARCHAR(25) NOT NULL,
  `nome_forne_prod` VARCHAR(45) NOT NULL,
  `preco_custo` DECIMAL(10,2) NOT NULL,
  `preco_venda` DECIMAL(10,2) NOT NULL,
  `preco_desc` DECIMAL(10,2),
  `coment_prod` VARCHAR(220),
  PRIMARY KEY (`id_prod`),
  UNIQUE INDEX `nome_prod_UNIQUE` (`nome_prod` ASC),
  UNIQUE INDEX `cod_barras_prod_UNIQUE` (`cod_barras_prod` ASC)
  )
GO
INSERT INTO tb_produto VALUES(1,'Chayds complete','10','30','0',0.140,00001,curdate(),'Joventude Eterna',3500,25,'jovens com uma vida agitada','789000001','Chayds Interno',40.00,60.90,00.00,'Produto voltado para jovens com uma vida agitada'),
(2,'Vita Chayds complet','10','30','0',0.140,00002,curdate(),'Chayds completo',3500,25,'jovens, adultos e idosos com uma vida agitada','789000002','Chayds Interno',40.00,60.90,00.00,'Produto voltado para jovens, adultos e idosos com uma vida agitada'),
(3,'Vita Chayd youg live','10','30','0',0.140,00003,curdate(),'Teste',3500,25,'teste','789000003','Chayds Interno',40.00,60.90,00.00,'Produto voltado para jovens com uma vida agitada')
GO
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;