-- MySQL Script generated by MySQL Workbench
-- Fri Jun  8 11:32:01 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `chayds_teste` DEFAULT CHARACTER SET utf8 ;
USE `chayds_teste` ;

-- COGIGO PARA MUDAR OS CARACTERES DO BANCO PARA RECONHECER PT-BR
-- ALTER DATABASE `sua_base` CHARSET = Latin1 COLLATE = latin1_swedish_ci;

-- -----------------------------------------------------
-- Table `mydb`.`tb_produto`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `chayds_teste`.`tbCompra` (
  `idCompra` INT NOT NULL AUTO_INCREMENT,
  `idComprador` INT,
  `idCarrinho` INT,
  `idProdutoCompra` INT,
  `nomeComprador` VARCHAR(50),
  `nomeCompra` VARCHAR(50),
  `emailComprador` VARCHAR(60),
  `quantidadeProduto` INT,
  `dataCompra` DATE,
  `valorFrete` DECIMAL(10,2),
  `precoVenda` DECIMAL(10,2),
  `valorTotal` DECIMAL(10,2),
  `cpfComprador` VARCHAR(18),
  `comentarioCompra` VARCHAR(200),
  `statusCompra` VARCHAR(25),
  `tipoFrete` VARCHAR(8),
  `codigoRastreio` VARCHAR(15),
  `imagemCompra` VARCHAR(80),
  `totalAltura` DECIMAL(5,2),
  `totalLargura` DECIMAL(5,2),
  `totalComprimento` DECIMAL(5,2),
  `totalPeso` DECIMAL(5,2),
  `video` VARCHAR(80),
  PRIMARY KEY (`idCompra`)
  )
GO
INSERT INTO tbCompra(idComprador, idCarrinho, idProdutoCompra, nomeComprador, nomeCompra, emailComprador, quantidadeProduto, dataCompra, valorFrete, precoVenda, valorTotal, cpfComprador, comentarioCompra, statusCompra, tipoFrete, codigoRastreio, imagemCompra, totalAltura, totalLargura, totalComprimento, totalPeso, video)
VALUES(1,'',1,'Alessandro dos Santos', 'Maka Black','alessandro@chayds.com.br',10,curdate(),19.50,60.90,609.00,'123456789','',25, 'S', 'RA1234569BR', 'img2.png', 70.00, 50.00, 50.00, 5.00, 'https://www.youtube.com/embed/1MPVyqoH8WM'),
(1,'',1,'Alessandro dos Santos', 'Maka Black','alessandro@chayds.com.br',10,curdate(),19.50,60.90,609.00,'123456789','',25, 'S', 'RA1234569BR', 'img2.png', 70.00, 50.00, 50.00, 5.00, 'https://www.youtube.com/embed/1MPVyqoH8WM'),
(1,'',1,'Alessandro dos Santos', 'Maka Black','alessandro@chayds.com.br',10,curdate(),19.50,60.90,609.00,'123456789','',25, 'S', 'RA1234569BR', 'img2.png', 70.00, 50.00, 50.00, 5.00, 'https://www.youtube.com/embed/1MPVyqoH8WM')
GO
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;